openapi: 3.0.0

info:
  title: API do InsideOut
  description: API do programa de gerenciamento de estoque InsideOut
  version: '0.0.1'

servers:
  - url: '/api'

paths:
  /test_api:
    get:
      operationId: routes.test_api.show_test
      tags:
        - Testing_swagger
      summary: Test route for testing the thingy
      responses:
        200:
          description: "API testada com sucesso"